"""empty message

Revision ID: 126e76cff57
Revises: 4aa215c325c
Create Date: 2015-12-16 20:34:22.458393

"""

# revision identifiers, used by Alembic.
revision = '126e76cff57'
down_revision = '4aa215c325c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='worker_pkey')
    )
    ### end Alembic commands ###
