"""empty message

Revision ID: 14b2de636f3
Revises: 4b577a2072c
Create Date: 2015-12-20 15:15:43.022629

"""

# revision identifiers, used by Alembic.
revision = '14b2de636f3'
down_revision = '4b577a2072c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'url')
    ### end Alembic commands ###
