"""empty message

Revision ID: 19b3057eb63
Revises: 3c5049dcae8
Create Date: 2015-12-17 16:37:24.845618

"""

# revision identifiers, used by Alembic.
revision = '19b3057eb63'
down_revision = '3c5049dcae8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('result_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'result', ['result_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'result_id')
    ### end Alembic commands ###
