"""empty message

Revision ID: 1aa28492094
Revises: 1aac2bb76a9
Create Date: 2015-12-14 19:41:26.464882

"""

# revision identifiers, used by Alembic.
revision = '1aa28492094'
down_revision = '1aac2bb76a9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'crawl_all')
    op.drop_column('image', 'image_all')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_all', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('crawl', sa.Column('crawl_all', postgresql.JSON(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
