"""empty message

Revision ID: 1aac2bb76a9
Revises: 9dd6d98058
Create Date: 2015-12-08 17:42:17.435743

"""

# revision identifiers, used by Alembic.
revision = '1aac2bb76a9'
down_revision = '9dd6d98058'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('url', sa.String(), nullable=True))
    op.add_column('image', sa.Column('source', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'source')
    op.drop_column('crawl', 'url')
    ### end Alembic commands ###
