"""empty message

Revision ID: 1bee1275997
Revises: 1aa28492094
Create Date: 2015-12-16 12:40:02.754310

"""

# revision identifiers, used by Alembic.
revision = '1bee1275997'
down_revision = '1aa28492094'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_crawl_id_fkey', 'image', type_='foreignkey')
    op.drop_column('image', 'crawl_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('crawl_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('image_crawl_id_fkey', 'image', 'crawl', ['crawl_id'], ['id'])
    ### end Alembic commands ###
