"""empty message

Revision ID: 1d25b8451fc
Revises: 14b2de636f3
Create Date: 2015-12-20 16:16:18.553276

"""

# revision identifiers, used by Alembic.
revision = '1d25b8451fc'
down_revision = '14b2de636f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('job_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'job_id')
    ### end Alembic commands ###
