"""empty message

Revision ID: 352b4f2bc82
Revises: 1bee1275997
Create Date: 2015-12-16 12:44:38.957838

"""

# revision identifiers, used by Alembic.
revision = '352b4f2bc82'
down_revision = '1bee1275997'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('crawl_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'crawl', ['crawl_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'crawl_id')
    ### end Alembic commands ###
