"""empty message

Revision ID: 3992f9e791d
Revises: 4a46b01a8f6
Create Date: 2015-12-16 17:19:00.543199

"""

# revision identifiers, used by Alembic.
revision = '3992f9e791d'
down_revision = '4a46b01a8f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crawl_job_id_fkey', 'crawl', type_='foreignkey')
    op.drop_column('crawl', 'job_id')
    op.drop_constraint('worker_job_id_fkey', 'worker', type_='foreignkey')
    op.drop_column('worker', 'job_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('worker_job_id_fkey', 'worker', 'crawl', ['job_id'], ['id'])
    op.add_column('crawl', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('crawl_job_id_fkey', 'crawl', 'job', ['job_id'], ['id'])
    ### end Alembic commands ###
