"""empty message

Revision ID: 3c5049dcae8
Revises: 126e76cff57
Create Date: 2015-12-17 10:31:19.207687

"""

# revision identifiers, used by Alembic.
revision = '3c5049dcae8'
down_revision = '126e76cff57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('crawl', sa.Column('result_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crawl', 'result', ['result_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crawl', type_='foreignkey')
    op.drop_column('crawl', 'result_id')
    op.drop_table('result')
    ### end Alembic commands ###
