"""empty message

Revision ID: 3d8fe5e3cac
Revises: 16b781edba9
Create Date: 2015-12-07 18:14:15.941612

"""

# revision identifiers, used by Alembic.
revision = '3d8fe5e3cac'
down_revision = '16b781edba9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'crawl_all')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('crawl_all', postgresql.JSON(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
