"""empty message

Revision ID: 48b5c9d1815
Revises: fd2976af2a
Create Date: 2015-12-07 16:01:43.247759

"""

# revision identifiers, used by Alembic.
revision = '48b5c9d1815'
down_revision = 'fd2976af2a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crawl_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], name='image_crawl_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_pkey')
    )
    ### end Alembic commands ###
