"""empty message

Revision ID: 4a46b01a8f6
Revises: 101df08753
Create Date: 2015-12-16 15:39:16.087582

"""

# revision identifiers, used by Alembic.
revision = '4a46b01a8f6'
down_revision = '101df08753'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('crawl_all', postgresql.JSON(), nullable=True))
    op.add_column('crawl', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crawl', 'job', ['job_id'], ['id'])
    op.add_column('image', sa.Column('image_all', postgresql.JSON(), nullable=True))
    op.add_column('job', sa.Column('job_all', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_all')
    op.drop_column('image', 'image_all')
    op.drop_constraint(None, 'crawl', type_='foreignkey')
    op.drop_column('crawl', 'job_id')
    op.drop_column('crawl', 'crawl_all')
    ### end Alembic commands ###
