"""empty message

Revision ID: 4b577a2072c
Revises: 1d2f8da56a3
Create Date: 2015-12-19 13:57:08.034341

"""

# revision identifiers, used by Alembic.
revision = '4b577a2072c'
down_revision = '1d2f8da56a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('result_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crawl', 'result', ['result_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crawl', type_='foreignkey')
    op.drop_column('crawl', 'result_id')
    ### end Alembic commands ###
