"""empty message

Revision ID: fd2976af2a
Revises: fbb522b472
Create Date: 2015-12-04 19:18:33.630848

"""

# revision identifiers, used by Alembic.
revision = 'fd2976af2a'
down_revision = 'fbb522b472'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('crawl_all', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.Column('image_all', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('crawl')
    ### end Alembic commands ###
